import json
import os

class LocalizationManager:
    """
    Manages multi-language support (English and Spanish).
    Loads translations from a dictionary and provides a get() method.
    """
    def __init__(self, language="en"):
        self.language = language
        # Dictionary of all translations
        self._translations = {
            # --- ENGLISH ---
            "en": {
                # Sidebar / Navigation
                "sidebar_home": "Home",
                "sidebar_upload": "Upload",
                "sidebar_history": "History",
                "sidebar_settings": "Settings",
                "sidebar_update": "Update",
                
                # Logo
                "logo_ai_shorts": "AI SHORTS",
                "logo_generator": "GENERATOR",
                "logo_pro": "PRO",
                
                # Home View
                "home_title": "Welcome back!",
                "home_subtitle1": "Ready to go viral today?",
                "home_subtitle2": "Manage your automated content generation and distribution from one place.",
                "tag_ai_powered": "AI POWERED",
                "stat_total_videos": "Total Videos",
                "stat_uploaded_videos": "Uploaded",
                "stat_last_gen": "Last Gen",
                "stat_pro": "Pro Edition",
                "btn_create_new": "Create New Video",
                "lbl_quick_actions": "Quick Actions",
                "lbl_recent_gen": "Recent Generations",
                "lbl_view_all": "View All",
                "qa_generate": "Generate",
                "qa_upload": "Upload",
                "qa_history": "History",
                "msg_loading_hist": "Loading recent activity...",
                "msg_no_recent_gen": "No recent generations found.",
                "lbl_ideas": "Ideas",
                
                # Generator View
                "title_generator": "Video Generator",
                "lbl_count": "Quantity",
                "lbl_topic": "Custom Topic (Optional)",
                "ph_topic": "Enter a specific topic or leave empty for ideas",
                "lbl_style": "Style / Mode",
                "lbl_watermark": "Channel Watermark",
                "btn_generate": "GENERATE",
                "gen_test_btn": "GEN TEST",
                "gen_cancel_btn": "STOP",
                "msg_no_recent_gen_long": "No videos found in output folder.",
                "stat_total_vid_desc": "Total Videos Generated",
                "stat_upload_vid_desc": "Videos Uploaded to YouTube",
                "stat_last_gen_desc": "Last Generation",
                
                # Progress / Status
                "status_starting": "Initializing...",
                "status_done": "Done!",
                "status_error": "Error: {0}",
                "status_cancelled": "Cancelled",
                "status_processing": "Processing {0} video(s)...",
                "status_gen_cancel": "Status: Cancelled by user.",
                "status_gen_done": "Status: Completed successfully!",
                "status_gen_error": "Status: Error occurred ({0})",
                "status_test_processing": "Status: Processing 1 TEST video. Please check logs for details.",
                "status_test_starting": "Status: Starting TEST generation in {0} mode...",
                "status_test_cancel": "Status: Test Cancelled.",
                "status_test_done": "Status: Test Completed successfully!",
                "mode_custom": "Custom",
                "mode_curiosity": "Curiosity",
                "mode_whatif": "What If?",
                "mode_top3": "Top 3",
                "mode_darkfacts": "Dark Facts",
                "mode_history": "History",
                "btn_open_output": "Open Output",

                # History View
                "title_history": "History",
                "msg_history_desc": "Review, play, or delete your previously generated videos.",
                "hist_filter_all": "All",
                "hist_filter_gen": "Generated",
                "hist_filter_up": "Uploaded",
                "hist_filter_del": "Deleted",
                "hist_col_video": "VIDEO",
                "hist_col_status": "STATUS",
                "hist_col_time": "TIME",
                "badge_generated": "Generated",
                "badge_uploaded": "Uploaded",
                "badge_cancelled": "Cancelled",
                "msg_no_history": "No history found in the output folder.",
                
                # Upload View
                "title_upload": "YouTube Uploader",
                "upload_folder_msg": "Videos in Output Folder",
                "upload_select_all": "Select All",
                "btn_login_google": "Login with Google",
                "tooltip_open_folder": "Open Folder",
                "tooltip_delete_video": "Delete Video",
                "msg_no_files": "No video files found in output directory.",
                "msg_select_video": "Please select at least one video to upload.",
                "msg_login_open": "A Chrome window will open. Log in to your YouTube account and close the window when done.",
                "title_upload_config": "Upload Configuration",
                "btn_schedule_intervals": "Schedule with Intervals",
                "btn_apply_intervals": "Apply Schedule",
                "lbl_start_date": "Starting From",
                "lbl_from": "From:",
                "lbl_interval": "Interval:",
                "opt_same_time": "At the same time",
                "opt_1_hour": "Every 1 hour",
                "opt_2_hours": "Every 2 hours",
                "opt_3_hours": "Every 3 hours",
                "opt_4_hours": "Every 4 hours",
                "opt_6_hours": "Every 6 hours",
                "opt_12_hours": "Every 12 hours",
                "opt_24_hours": "Every 24 hours",
                "lbl_unprogrammed": "Direct Upload",
                "msg_unprogrammed_upload_now": "Unscheduled videos will be uploaded immediately one after another.",
                "opt_upload_now": "Upload Now",
                "opt_schedule": "Schedule",
                "tooltip_schedule_date": "Schedule specific date/time",
                "msg_invalid_date_format": "Invalid date format. Use DD/MM/YYYY HH:MM",
                "msg_invalid_date_for_video": "Invalid date for {video_title}",
                "msg_error_opening_panel": "Error opening upload panel",
                "msg_intervals_applied": "Intervals applied to list. Please click Confirm.",
                "badge_generated": "Generated",
                "badge_uploaded": "Uploaded",
                "progress_preparing": "Preparing...",
                "progress_starting": "Starting...",
                "progress_uploading": "Uploading...",
                "progress_completed": "Completed!",
                "progress_cancelled": "Cancelled",
                "tooltip_cancel": "Cancel upload",
                "btn_upload": "Upload Videos",
                "btn_confirm": "Confirm",
                "btn_cancel": "Cancel",
                "btn_delete": "Delete",
                "title_confirm_deletion": "Confirm Deletion",
                "msg_confirm_delete_video": "Are you sure you want to delete this video folder?",
                "msg_video_deleted": "Video folder deleted.",
                "msg_error_deleting": "Error deleting folder",
                "status_google_connected": "Google: Connected",
                "msg_login_success": "Google Login successful!",
                "title_confirm_logout": "Confirm Logout",
                "msg_confirm_logout": "Are you sure you want to log out of Google?",
                "btn_logout": "Log Out",
                "msg_logged_out": "Successfully logged out of Google.",
                
                # Date Filters
                "opt_all_dates": "All",
                "opt_today": "Today",
                "opt_yesterday": "Yesterday",
                "opt_last_week": "Last week",
                "opt_last_month": "Last month",
                
                # Settings View
                "title_settings": "Settings & API Keys",
                "lbl_api_keys": "API KEYS",
                "lbl_google_key": "Google Gemini API Key",
                "lbl_pexels_key": "Pexels API Key",
                "lbl_preferences": "PREFERENCES",
                "lbl_language": "App Language",
                "btn_save": "SAVE SETTINGS",
                "lbl_support": "Support",
                "lbl_visit_website": "Visit my website",
                "tooltip_visit_website": "Go to official page",
                "msg_history_cleaned": "✅ History successfully cleaned.",
                "msg_error_cleaning_history": "Error cleaning history",
                "title_empty_history_all": "⚠️ Empty Entire History",
                "msg_empty_history_all": "Are you sure you want to delete ALL history?\nThis will permanently delete all videos, metadata, and local records.",
                "btn_clean_all": "Yes, Clean All",
                "btn_clean_history": "Clean History",
                "msg_loading_hist": "Loading history...",
                "msg_error_opening_folder": "Error opening folder",
                "tooltip_open_folder2": "Open Folder",
                "tooltip_delete2": "Delete",
                "msg_error_loading_history": "Error loading history",
                "msg_error_loading_upload": "Error loading upload UI",
                "msg_process_error": "Process Error",
                "msg_thread_error": "Error starting process",
                
                # Update View
                "sidebar_update": "Update",
                "update_title": "Upgrade to Premium",
                "update_subtitle": "Unlock the full potential of AI automation",
                "update_col_feature": "FEATURE",
                "update_feat_duration": "Video Duration",
                "update_feat_duration_pro": "Up to 60s",
                "update_feat_duration_prem": "Unlimited",
                "update_feat_effects": "Visual Effects",
                "update_feat_effects_pro": "Basic",
                "update_feat_effects_prem": "Premium VFX",
                "update_feat_transitions": "Transitions",
                "update_feat_transitions_pro": "Standard",
                "update_feat_transitions_prem": "Cinematic",
                "update_feat_quality": "Video Quality",
                "update_feat_quality_pro": "1080p",
                "update_feat_quality_prem": "4K Ultra HD",
                "update_feat_speed": "Generation Speed",
                "update_feat_speed_pro": "Standard",
                "update_feat_speed_prem": "Turbo 2x",
                "update_feat_support": "Priority Support",
                "update_feat_support_pro": "Email",
                "update_feat_support_prem": "24/7 Chat + Email",
                "update_feat_updates": "New Features",
                "update_feat_updates_pro": "Standard",
                "update_feat_updates_prem": "Early Access",
                "update_btn_get": "GET PREMIUM NOW",
                "update_snack_contact": "Contact tiagoaccotos@gmail.com for upgrade details.",
                
                # Miscellaneous
                "lbl_info": "Information",
                "lbl_error": "Error",
                "lbl_warning": "Warning",
                "msg_unexpected_error": "An unexpected error occurred: {0}",
                "msg_login_required": "Login required to proceed.",
                "msg_cleaning": "Cleaning temporary files...",
                "msg_cleaning_done": "Cleaning completed."
            },
            
            # --- SPANISH ---
            "es": {
                # Sidebar / Navegación
                "sidebar_home": "Inicio",
                "sidebar_upload": "Subir",
                "sidebar_history": "Historial",
                "sidebar_settings": "Ajustes",
                "sidebar_update": "Actualizar",
                
                # Logo
                "logo_ai_shorts": "AI SHORTS",
                "logo_generator": "GENERADOR",
                "logo_pro": "PRO",
                
                # Vista de Inicio
                "home_title": "¡Bienvenido!",
                "home_subtitle1": "¿Listo para ser viral hoy?",
                "home_subtitle2": "Gestiona tu generación y distribución de contenido automatizado desde un solo lugar.",
                "tag_ai_powered": "IA POTENCIADA",
                "stat_total_videos": "Videos Totales",
                "stat_uploaded_videos": "Subidos",
                "stat_last_gen": "Última Gen",
                "stat_pro": "Edición Pro",
                "btn_create_new": "Crear Nuevo Video",
                "lbl_quick_actions": "Acciones Rápidas",
                "lbl_recent_gen": "Generaciones Recientes",
                "lbl_view_all": "Ver Todo",
                "qa_generate": "Generar",
                "qa_upload": "Subir",
                "qa_history": "Historial",
                "msg_loading_hist": "Cargando actividad reciente...",
                "msg_no_recent_gen": "No se encontraron generaciones recientes.",
                "lbl_ideas": "Ideas",
                
                # Vista de Generador
                "title_generator": "Generador de Video",
                "lbl_count": "Cantidad",
                "lbl_topic": "Tema Personalizado (Opcional)",
                "ph_topic": "Ingresa un tema específico o deja vacío para ideas",
                "lbl_style": "Estilo / Modo",
                "lbl_watermark": "Marca de Agua",
                "btn_generate": "GENERAR",
                "gen_test_btn": "GEN TEST",
                "gen_cancel_btn": "PARAR",
                "msg_no_recent_gen_long": "No se encontraron videos en la carpeta de salida.",
                "stat_total_vid_desc": "Videos Totales Generados",
                "stat_upload_vid_desc": "Videos Subidos a YouTube",
                "stat_last_gen_desc": "Última Generación",
                
                # Progreso / Estado
                "status_starting": "Iniciando...",
                "status_done": "¡Hecho!",
                "status_error": "Error: {0}",
                "status_cancelled": "Cancelado",
                "status_processing": "Procesando {0} video(s)...",
                "status_gen_cancel": "Estado: Cancelado por el usuario.",
                "status_gen_done": "Estado: ¡Completado con éxito!",
                "status_gen_error": "Estado: Ocurrió un error ({0})",
                "status_test_processing": "Estado: Procesando 1 video de PRUEBA.",
                "status_test_starting": "Estado: Iniciando prueba en modo {0}...",
                "status_test_cancel": "Estado: Prueba Cancelada.",
                "status_test_done": "Estado: ¡Prueba Completada con éxito!",
                "mode_custom": "Personalizado",
                "mode_curiosity": "Curiosidad",
                "mode_whatif": "¿Y si...?",
                "mode_top3": "Top 3",
                "mode_darkfacts": "Hechos Oscuros",
                "mode_history": "Historia",
                "btn_open_output": "Abrir Carpeta",

                # Vista de Historial
                "title_history": "Historial",
                "msg_history_desc": "Revisa, reproduce o elimina tus videos generados anteriormente.",
                "hist_filter_all": "Todos",
                "hist_filter_gen": "Generados",
                "hist_filter_up": "Subidos",
                "hist_filter_del": "Eliminados",
                "hist_col_video": "VIDEO",
                "hist_col_status": "ESTADO",
                "hist_col_time": "FECHA",
                "badge_generated": "Generado",
                "badge_uploaded": "Subido",
                "badge_cancelled": "Cancelado",
                "msg_no_history": "No se encontró historial en la carpeta de salida.",
                
                # Vista de Subida
                "title_upload": "Subidor de YouTube",
                "upload_folder_msg": "Videos en Carpeta de Salida",
                "upload_select_all": "Seleccionar Todos",
                "btn_login_google": "Iniciar Sesión con Google",
                "tooltip_open_folder": "Abrir Carpeta",
                "tooltip_delete_video": "Eliminar Video",
                "msg_no_files": "No se encontraron archivos de video en el directorio de salida.",
                "msg_select_video": "Por favor, selecciona al menos un video para subir.",
                "msg_login_open": "Se abrirá una ventana de Chrome. Inicia sesión en tu cuenta de YouTube y cierra la ventana al terminar.",
                "title_upload_config": "Configuración de Subida",
                "btn_schedule_intervals": "Programar con Intervalos",
                "btn_apply_intervals": "Aplicar Horarios",
                "lbl_start_date": "Empezando desde",
                "lbl_from": "Desde:",
                "lbl_interval": "Intervalo:",
                "opt_same_time": "Al mismo tiempo",
                "opt_1_hour": "Cada 1 hora",
                "opt_2_hours": "Cada 2 horas",
                "opt_3_hours": "Cada 3 horas",
                "opt_4_hours": "Cada 4 horas",
                "opt_6_hours": "Cada 6 horas",
                "opt_12_hours": "Cada 12 horas",
                "opt_24_hours": "Cada 24 horas",
                "lbl_unprogrammed": "Subida Directa",
                "msg_unprogrammed_upload_now": "Los videos no programados se subirán inmediatamente uno tras otro.",
                "opt_upload_now": "Subir Ahora",
                "opt_schedule": "Programar",
                "tooltip_schedule_date": "Programar fecha/hora específica",
                "msg_invalid_date_format": "Formato de fecha inválido. Usa DD/MM/AAAA HH:MM",
                "msg_invalid_date_for_video": "Fecha inválida para {video_title}",
                "msg_error_opening_panel": "Error al abrir el panel de subida",
                "msg_intervals_applied": "Intervalos aplicados a la lista. Por favor, haz clic en Confirmar.",
                "progress_preparing": "Preparando...",
                "progress_starting": "Iniciando...",
                "progress_uploading": "Subiendo...",
                "progress_completed": "¡Completado!",
                "progress_cancelled": "Cancelado",
                "tooltip_cancel": "Cancelar subida",
                "btn_upload": "Subir Videos",
                "btn_confirm": "Confirmar",
                "btn_cancel": "Cancelar",
                "btn_delete": "Eliminar",
                "title_confirm_deletion": "Confirmar Eliminación",
                "msg_confirm_delete_video": "¿Estás seguro de que deseas eliminar la carpeta de este video?",
                "msg_video_deleted": "Carpeta de video eliminada.",
                "msg_error_deleting": "Error al eliminar la carpeta",
                "status_google_connected": "Google: Conectado",
                "msg_login_success": "¡Login a Google exitoso!",
                "title_confirm_logout": "Confirmar Cierre de Sesión",
                "msg_confirm_logout": "¿Estás seguro de que deseas desconectar tu cuenta de Google?",
                "btn_logout": "Cerrar Sesión",
                "msg_logged_out": "Se ha cerrado la sesión de Google correctamente.",
                
                # Filtros de Fecha
                "opt_all_dates": "Todos",
                "opt_today": "Hoy",
                "opt_yesterday": "Ayer",
                "opt_last_week": "Última semana",
                "opt_last_month": "Último mes",
                
                # Vista de Ajustes
                "title_settings": "Ajustes y Claves API",
                "lbl_api_keys": "CLAVES API",
                "lbl_google_key": "Clave API Google Gemini",
                "lbl_pexels_key": "Clave API Pexels",
                "lbl_preferences": "PREFERENCIAS",
                "lbl_language": "Idioma de la App",
                "btn_save": "GUARDAR AJUSTES",
                "lbl_support": "Soporte",
                "lbl_visit_website": "Visitar mi página web",
                "tooltip_visit_website": "Ir a la página oficial",
                "msg_history_cleaned": "✅ Historial limpiado completamente.",
                "msg_error_cleaning_history": "Error limpiando historial",
                "title_empty_history_all": "⚠️ Vaciar Historial Completo",
                "msg_empty_history_all": "¿Estás seguro de que quieres eliminar TODO el historial?\nEsto borrará permanentemente todos los videos, metadatos y registros locales.",
                "btn_clean_all": "Sí, Limpiar Todo",
                "btn_clean_history": "Limpiar Historial",
                "msg_loading_hist": "Cargando historial...",
                "msg_error_opening_folder": "Error al abrir la carpeta",
                "tooltip_open_folder2": "Abrir Carpeta",
                "tooltip_delete2": "Eliminar",
                "msg_error_loading_history": "Error cargando historial",
                "msg_error_loading_upload": "Error cargando subida",
                "msg_process_error": "Error de Proceso",
                "msg_thread_error": "Error iniciando proceso",
                
                # Vista de Actualización
                "sidebar_update": "Actualizar",
                "update_title": "Mejorar a Premium",
                "update_subtitle": "Desbloquea todo el potencial de la automatización por IA",
                "update_col_feature": "CARACTERÍSTICA",
                "update_feat_duration": "Duración de Video",
                "update_feat_duration_pro": "Hasta 60s",
                "update_feat_duration_prem": "Ilimitado",
                "update_feat_effects": "Efectos Visuales",
                "update_feat_effects_pro": "Básicos",
                "update_feat_effects_prem": "VFX Premium",
                "update_feat_transitions": "Transiciones",
                "update_feat_transitions_pro": "Estándar",
                "update_feat_transitions_prem": "Cinematográficas",
                "update_feat_quality": "Calidad de Video",
                "update_feat_quality_pro": "1080p",
                "update_feat_quality_prem": "4K Ultra HD",
                "update_feat_speed": "Velocidad de Gen",
                "update_feat_speed_pro": "Estándar",
                "update_feat_speed_prem": "Turbo 2x",
                "update_feat_support": "Soporte Prioritario",
                "update_feat_support_pro": "Email",
                "update_feat_support_prem": "Chat 24/7 + Email",
                "update_feat_updates": "Nuevas Características",
                "update_feat_updates_pro": "Estándar",
                "update_feat_updates_prem": "Acceso Anticipado",
                "update_btn_get": "OBTENER PREMIUM AHORA",
                "update_snack_contact": "Contacta a tiagoaccotos@gmail.com para detalles de mejora.",
                
                # Misceláneo
                "lbl_info": "Información",
                "lbl_error": "Error",
                "lbl_warning": "Advertencia",
                "msg_unexpected_error": "Ocurrió un error inesperado: {0}",
                "msg_login_required": "Se requiere iniciar sesión para continuar.",
                "msg_cleaning": "Limpiando archivos temporales...",
                "msg_cleaning_done": "Limpieza completada."
            }
        }

    def get(self, key, default=None):
        """Returns the translation for the given key in the current language."""
        return self._translations.get(self.language, {}).get(key, self._translations.get("en", {}).get(key, default or key))

    def set_language(self, language_code):
        """Changes the current language."""
        if language_code in self._translations:
            self.language = language_code
        else:
            # Fallback to English if code not found
            self.language = "en"
